### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by Toothless3108** [sell/discord-tutorial-bot#30]
I am getting this error

C:\Users\malan\Downloads\discord-tutorial-bot-master\discord-tutorial-bot-master>node index.js
C:\Users\malan\Downloads\discord-tutorial-bot-master\discord-tutorial-bot-master\node_modules\discord.js\src\client\Client.js:204
    if (!token || typeof token !== 'string') throw new Error('TOKEN_INVALID');
                                                   ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\malan\Downloads\discord-tutorial-bot-master\discord-tutorial-bot-master\node_modules\←[4mdiscord.js←[24m\src\client\Client.js:204:52)
    at Object.<anonymous> (C:\Users\malan\Downloads\discord-tutorial-bot-master\discord-tutorial-bot-master\index.js:27:8)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  [←[32mSymbol(code)←[39m]: ←[32m'TOKEN_INVALID'←[39m
}

**Comment by RainyXeon** [comment]
@fade-dev I think the token you provided to the bot is invalid, try reset the token of the bot, paste the token and run it again.
